import React from "react";
import Providers from "../components/providers";
import Layout from "../components/layout";
import "../styles/index.scss"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Providers>
        <Layout>
          <body>{children}</body>
        </Layout>
      </Providers>
    </html>
  )
}
