import {
  pageWidthThemes,
  cursorThemes,
  pageTransitionThemes,
  gridThemes,
  gridColumns,
  gridGap,
  gridGalleryThemes,
  textAnimationThemes,
  typographyThemes,
  fontScaleThemes,
  textHighlightThemes,
  textHighlightOutlineThemes,
  bodyTextAlign,
  navigationPositionThemes,
  navigationStyleThemes,
  navigationThemes,
  navigationOptions,
  heroHeightThemes,
  heroTypeThemes,
  heroBackgroundThemes,
  heroCssGradientThemes
  ,
  heroCssGradientRadialPositionThemes,
  heroTextImageThemes,
  heroTextPositionThemes,
  heroTextCompositionThemes,
  cardThemes,
  cardHoverThemes,
  mixBlendThemes,
  imageTextureThemes,
} from "./theme";

export const themeControlConfig = {
  Audio: {
    audioEnabled: { type: "boolean", label: "Audio" },
    audioVolume: { type: "slider", label: "Volume", min: 0, max: 1, step: 0.1 },
    init: { type: "select", label: "Internal Link Hover", options: typographyThemes },
    primaryButton: { type: "select", label: "Primary Button", options: typographyThemes },
    secondaryButton: { type: "select", label: "Secondary Button", options: typographyThemes },
    internalLink: { type: "select", label: "Primary Link", options: typographyThemes },
    externalLink: { type: "select", label: "Secondary Link", options: typographyThemes },
    pageTransitionStart: { type: "select", label: "Page Transition Start", options: typographyThemes },
    pageTransitionEnd: { type: "select", label: "Page Transition End", options: typographyThemes },
    modalOpen: { type: "select", label: "Modal Open", options: typographyThemes },
    modalClose: { type: "select", label: "Modal Close", options: typographyThemes },
  },
  Globals: {
    pageWidth: { type: "select", label: "Page Width", options: pageWidthThemes },
    cursor: { type: "select", label: "Cursor", options: cursorThemes },
    pageTransition: { type: "select", label: "Page Transition", options: pageTransitionThemes },
    cardGrid: { type: "select", label: "Grid", options: gridThemes },
    gridColumnsSm: { type: "select", label: "Sm", options: gridColumns },
    gridColumnsMd: { type: "select", label: "Md", options: gridColumns },
    gridColumnsLg: { type: "select", label: "Lg", options: gridColumns },
    gridColumnsXl: { type: "select", label: "Xl", options: gridColumns },
    gridGap: { type: "select", label: "Grid Gap", options: gridGap },
    gridGallery: { type: "select", label: "Grid Gallery", options: gridGalleryThemes },
    cardLayout: { type: "select", label: "Layout", options: cardThemes },
    cardHover: { type: "select", label: "Hover", options: cardHoverThemes },
  },
  Typography: {
    textAnimation: { type: "select", label: "Text Animation", options: textAnimationThemes },
    textAnimationSec: { type: "select", label: "Text Anim Sec", options: textAnimationThemes },
    fontFamilyPrimary: { type: "select", label: "Font Family Primary", options: typographyThemes },
    fontFamilySecondary: { type: "select", label: "Font Family Secondary", options: typographyThemes },
    fontScale: { type: "select", label: "Scale", options: fontScaleThemes },
    fluidFontRatioMax: { type: "slider", label: "Fluid Max", min: 0, max: 1.3, step: 0.01 },
    fluidFontRatioMin: { type: "slider", label: "Fluid Min", min: 0, max: 1.3, step: 0.01 },
    textHighlight: { type: "select", label: "Text Highlight", options: textHighlightThemes },
    textHighlightOutline: { type: "select", label: "Text Highlight Outline", options: textHighlightOutlineThemes },
    BodyText: {
        isFolder: true,
        bodyTextDropCap: { type: "boolean", label: "Drop Cap" },
        bodyTextIndent: { type: "boolean", label: "Indent" },
        bodyTextHighlight: { type: "select", label: "Highlight", options: textHighlightThemes },
        bodyTextAlign: { type: "select", label: "Align", options: bodyTextAlign },
    }
  },
  Navigation: {
    navPosition: { type: "select", label: "Position", options: navigationPositionThemes },
    navStyle: { type: "select", label: "Style", options: navigationStyleThemes },
    navTheme: { type: "select", label: "Theme", options: navigationThemes },
    navLabelDisplay: { type: "select", label: "Label Display", options: navigationOptions.labelDisplay },
    navFloating: { type: "boolean", label: "Floating" },
    navFixed: { type: "boolean", label: "Fixed" },
    navBorder: { type: "boolean", label: "Border" },
    navShadow: { type: "boolean", label: "Shadow" },
    navShadowColor: { type: "select", label: "Shadow Color", options: navigationOptions.shadowColor },
    navShadowSize: { type: "select", label: "Shadow Size", options: navigationOptions.shadowSize },
  },
  Footer: {
    footerFixed: { type: "boolean", label: "Fixed" },
  },
  Hero: {
    heroHeight: { type: "select", label: "Height", options: heroHeightThemes },
    heroType: { type: "select", label: "Type", options: heroTypeThemes },
    heroBackgroundStyle: { type: "select", label: "Bg", options: heroBackgroundThemes },
    heroCssGradient: { type: "select", label: "CSS Gradient Type", options: heroCssGradientThemes },
    heroCssGradientAngle: { type: "slider", label: "CSS Gradient Angle", min: 0, max: 180, step: 1 },
    heroCssGradientRadialPosition: { type: "select", label: "CSS Gradient Radial Position", options: heroCssGradientRadialPositionThemes },
    heroGradMidPoint: { type: "slider", label: "Gradient Mid Point", min: 0, max: 1, step: 0.1 },
    heroTextImageStyle: { type: "select", label: "Images", options: heroTextImageThemes },
    heroTextPosition: { type: "position", label: "Text Layout", options: heroTextPositionThemes },
  },
  Images: {
    imageParallax: { type: "boolean", label: "Parallax" },
    imageMixBlendMode: { type: "select", label: "Blend Mode", options: mixBlendThemes },
    imageTexture: { type: "select", label: "Texture", options: imageTextureThemes },
    imageTextureContrast: { type: "slider", label: "Contrast", min: 0, max: 1000, step: 1, suffix: "%" },
    imageTextureBrightness: { type: "slider", label: "Brightness", min: 0, max: 1000, step: 1, suffix: "%" },
  },
  Color: {
    accentPri: { type: "color", label: "Accent Primary" },
    accentSec: { type: "color", label: "Accent Secondary" },
    accentImageBg: { type: "color", label: "Accent Image Bg" },
    backgroundColor: { type: "color", label: "Background Color" },
    backgroundColorInv: { type: "color", label: "Background Color Inverted" },
    bodyBackgroundColor: { type: "color", label: "Body Background Color" },
    gradStart: { type: "color", label: "Gradient Start" },
    gradStop: { type: "color", label: "Gradient Stop" },
    headingColor: { type: "color", label: "Heading Color" },
    navBg: { type: "color", label: "Navigation Background" },
    subtextColor: { type: "color", label: "Subtext Color" },
    surface1: { type: "color", label: "Surface 1" },
    surface2: { type: "color", label: "Surface 2" },
    surface3: { type: "color", label: "Surface 3" },
    textAccent: { type: "color", label: "Text Accent" },
    textColor: { type: "color", label: "Text Color" },
    textColorInv: { type: "color", label: "Text Color Inverted" },
  }
}; 