import {
  pageWidthThemes,
  cursorThemes,
  pageTransitionThemes,
  gridLayoutThemes,
  listLayoutThemes,
  gridColumns,
  gridGap,
  textAnimationThemes,
  typographyThemes,
  fontScaleThemes,
  textHighlightThemes,
  bodyTextAlign,
  footerOptions,
  navigationPositionThemes,
  navigationStyleThemes,
  navigationThemes,
  navigationOptions,
  heroBackgroundThemes,
  heroShaderEffectThemes,
  heroCssGradientThemes,
  heroCssGradientRadialPositionThemes,
  heroTextImageThemes,
  heroTextPositionThemes,
  heroTextColSpanThemes,
  heroTextColSpanLgThemes,
  headerTextPositionThemes,
  textAlignThemes,
  cardThemes,
  cardHoverThemes,
  cardAspectRatio,
  mixBlendThemes,
  imageTextureThemes,
  surfaceTexture,
  logoStyle,
  logoBackground,
  sounds,
  shaderEffect,
} from "./theme";


// audioInit: soundThemes.default,
// audioInternalLinkHover: typographyThemes.sans,
// audioPrimaryButton: soundThemes.default,
// audioSecondaryButton: soundThemes.default,
// audioInternalLink: soundThemes.default,
// audioExternalLink: soundThemes.default,
// audioPageTransitionStart: soundThemes.default,
// audioPageTransitionEnd: soundThemes.default,
// audioModalOpen: soundThemes.default,
// audioModalClose: soundThemes.default,

export const themeControlConfig = {
  Audio: {
    audioEnabled: { type: "boolean", label: "Audio" },
    audioVolume: { type: "slider", label: "Volume", min: 0, max: 1, step: 0.1 },
    audioInit: { type: "select", label: "Init", options: sounds },
    audioInternalLinkHover: { type: "select", label: "Internal Link Hover", options: sounds },
    audioPrimaryButton: { type: "select", label: "Primary Button", options: sounds },
    audioSecondaryButton: { type: "select", label: "Secondary Button", options: sounds },
    audioInternalLink: { type: "select", label: "Primary Link", options: sounds },
    audioExternalLink: { type: "select", label: "Secondary Link", options: sounds },
    audioPageTransitionStart: { type: "select", label: "Page Transition Start", options: sounds },
    audioPageTransitionEnd: { type: "select", label: "Page Transition End", options: sounds },
    audioModalOpen: { type: "select", label: "Modal Open", options: sounds },
    audioModalClose: { type: "select", label: "Modal Close", options: sounds },
  },
  Globals: {
    pageWidth: { type: "select", label: "Page Width", options: pageWidthThemes },
    cursor: { type: "select", label: "Cursor", options: cursorThemes },
    pageTransition: { type: "select", label: "Page Transition", options: pageTransitionThemes },
    gridType: { type: "select", label: "Grid Type", options: gridLayoutThemes },
    listType: { type: "select", label: "List Type", options: listLayoutThemes },
    gridColumnsSm: { type: "select", label: "Sm", options: gridColumns },
    gridColumnsMd: { type: "select", label: "Md", options: gridColumns },
    gridColumnsLg: { type: "select", label: "Lg", options: gridColumns },
    gridColumnsXl: { type: "select", label: "Xl", options: gridColumns },
    gridGap: { type: "select", label: "Grid Gap", options: gridGap },
    cardAspectRatio: { type: "select", label: "Aspect Ratio", options: cardAspectRatio },
    cardLayout: { type: "select", label: "Card Type", options: cardThemes },
    cardHover: { type: "select", label: "Hover", options: cardHoverThemes },
    cursor: { type: "select", label: "Cursor", options: cursorThemes },
  },
  Typography: {
    fontFamilyPrimary: { type: "select", label: "Font Family Primary", options: typographyThemes },
    fontFamilySecondary: { type: "select", label: "Font Family Secondary", options: typographyThemes },
    fontScale: { type: "select", label: "Scale", options: fontScaleThemes },
    fluidFontRatioMax: { type: "slider", label: "Fluid Max", min: 0, max: 1.3, step: 0.01 },
    fluidFontRatioMin: { type: "slider", label: "Fluid Min", min: 0, max: 1.3, step: 0.01 },
    headerTextAlign: { type: "select", label: "Header Align", options: textAlignThemes },
    blockquoteTextAlign: { type: "select", label: "Blockquote Align", options: textAlignThemes },
    BodyText: {
        isFolder: true,
        bodyTextDropCap: { type: "boolean", label: "Drop Cap" },
        bodyTextIndent: { type: "boolean", label: "Indent" },
        bodyTextHighlight: { type: "select", label: "Highlight", options: textHighlightThemes },
        bodyTextAlign: { type: "select", label: "Align", options: bodyTextAlign },
    }
  },
  TypographyAnimation: {
    textAnimation: { type: "select", label: "Text Animation", options: textAnimationThemes },
    textAnimationSec: { type: "select", label: "Text Anim Sec", options: textAnimationThemes },
    textHighlight: { type: "select", label: "Text Highlight", options: textHighlightThemes },

  },
  Hero: {
    heroHeight: { type: "slider", label: "Height (vh)", min: 10, max: 100, step: 5 },
    heroTextImage: { type: "select", label: "Images", options: heroTextImageThemes },
    heroTextPosition: { type: "position", label: "Text Layout", options: heroTextPositionThemes },
    heroTextColSpanDefault: { type: "select", label: "Text Col Span Default", options: heroTextColSpanThemes },
    heroTextColSpanLg: { type: "select", label: "Text Col Span Large", options: heroTextColSpanLgThemes },
    headerTextPosition: { type: "position", label: "Header Layout", options: headerTextPositionThemes },
    heroSubTextPosition: { type: "position", label: "Subtext Layout", options: heroTextPositionThemes },
    heroSubTextColSpanDefault: { type: "select", label: "Subtext Col Span Default", options: heroTextColSpanThemes },
    heroSubTextColSpanLg: { type: "select", label: "Subtext Col Span Large", options: heroTextColSpanLgThemes },
    heroTextAlign: { type: "select", label: "Text Align", options: textAlignThemes },
    heroSubTextAlign: { type: "select", label: "Subtext Align", options: textAlignThemes },
  },
  HeroBg: {
    heroBackground: { type: "select", label: "Bg", options: heroBackgroundThemes },
    heroShaderEffect: { type: "select", label: "Shader Effect", options: heroShaderEffectThemes },
    heroCssGradient: { type: "select", label: "CSS Gradient Type", options: heroCssGradientThemes },
    heroCssGradientAngle: { type: "slider", label: "CSS Gradient Angle", min: 0, max: 180, step: 1 },
    heroCssGradientRadialPosition: { type: "select", label: "CSS Gradient Radial Position", options: heroCssGradientRadialPositionThemes },
    heroGradMidPoint: { type: "slider", label: "Gradient Mid Point", min: 0, max: 1, step: 0.1 },
  },

  Navigation: {
    navPosition: { type: "select", label: "Position", options: navigationPositionThemes },
    navLayoutPosition: { type: "select", label: "Layout Position", options: navigationOptions.position},
    navStyle: { type: "select", label: "Style", options: navigationStyleThemes },
    navTheme: { type: "select", label: "Theme", options: navigationThemes },
    navLabelDisplay: { type: "select", label: "Label Display", options: navigationOptions.labelDisplay },
    navBorder: { type: "boolean", label: "Border" },
    navShadow: { type: "boolean", label: "Shadow" },
    navShadowColor: { type: "select", label: "Shadow Color", options: navigationOptions.shadowColor },
    navShadowSize: { type: "select", label: "Shadow Size", options: navigationOptions.shadowSize },
    logoBackground: { type: "select", label: "Logo Background", options: logoBackground },
    logoStyle: { type: "select", label: "Logo Style", options: logoStyle },
  },
  Footer: {
    footerPosition: { type: "select", label: "Position", options: footerOptions.position },
  },

  Images: {
    imageParallax: { type: "boolean", label: "Parallax" },
    imageMixBlendMode: { type: "select", label: "Blend Mode", options: mixBlendThemes },
    imageTexture: { type: "select", label: "Texture", options: imageTextureThemes },
    imageTextureContrast: { type: "slider", label: "Contrast", min: 0, max: 1000, step: 1, suffix: "%" },
    imageTextureBrightness: { type: "slider", label: "Brightness", min: 0, max: 1000, step: 1, suffix: "%" },
  },
  Color: {
    accentPri: { type: "color", label: "Accent Primary" },
    accentSec: { type: "color", label: "Accent Secondary" },
    accentImageBg: { type: "color", label: "Accent Image Bg" },
    backgroundColor: { type: "color", label: "Background Color" },
    backgroundColorInv: { type: "color", label: "Background Color Inverted" },
    bodyBackgroundColor: { type: "color", label: "Body Background Color" },
    gradStart: { type: "color", label: "Gradient Start" },
    gradStop: { type: "color", label: "Gradient Stop" },
    headingColor: { type: "color", label: "Heading Color" },
    navBg: { type: "color", label: "Navigation Background" },
    subtextColor: { type: "color", label: "Subtext Color" },
    surface1: { type: "color", label: "Surface 1" },
    surface2: { type: "color", label: "Surface 2" },
    surface3: { type: "color", label: "Surface 3" },
    textAccent: { type: "color", label: "Text Accent" },
    textColor: { type: "color", label: "Text Color" },
    textColorInv: { type: "color", label: "Text Color Inverted" },
    surfaceTexture: { type: "select", label: "Surface Texture", options: surfaceTexture },
  },
  Effects: {
    halftoneSize: { type: "slider", label: "Halftone Dot Size", min: 2, max: 20, step: 0.5 },
    asciiSize: { type: "slider", label: "ASCII Character Size", min: 6, max: 24, step: 1 },
    ditherLevels: { type: "slider", label: "Dither Color Levels", min: 2, max: 16, step: 1 },
    ditherSize: { type: "slider", label: "Dither Pattern Size", min: 2, max: 8, step: 1 },
    pixelationSize: { type: "slider", label: "Pixelation Size", min: 2, max: 32, step: 1 },
    noiseIntensity: { type: "slider", label: "Noise Intensity", min: 0, max: 1, step: 0.05 },
  },
  // Effects: {
  //   shaderType: { type: "select", label: "Shader Type", options: shaderTypes },
  //   shaderMesh: { type: "boolean", label: "Mesh" }, 
  //   pixelDensity: { type: "slider", label: "Pixel Density", min: 1, max: 100, step: 1 },
  //   halftoneSize: { type: "slider", label: "Halftone Size", min: 1, max: 20, step: 0.1 },
  //   halftoneShape: { type: "select", label: "Halftone Shape", options: { circle: "Circle", square: "Square" } },
  //   halftoneInvert: { type: "boolean", label: "Halftone Invert" },
  //   dotScale: { type: "slider", label: "Dot Scale", min: 0.1, max: 1.0, step: 0.1 },
  // },
}; 